# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-25 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox_id', models.IntegerField(default=0, verbose_name='MailBox')),
                ('mailbox', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u79bb\u804c\u5e10\u53f7')),
                ('mailbox_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u76ee\u6807\u5e10\u53f7')),
                ('mode', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8fc1\u79fb\u6a21\u5f0f')),
                ('succ_del', models.IntegerField(choices=[(b'1', '\u662f'), (b'-1', '\u5426')], default='-1', verbose_name='\u5220\u9664\u5e10\u53f7')),
                ('status', models.CharField(choices=[(b'wait', '\u7b49\u5f85\u5904\u7406'), (b'transfering', '\u6b63\u5728\u4f20\u8f93'), (b'transfered', '\u4f20\u8f93\u5b8c\u6bd5'), (b'deleting', '\u6b63\u5728\u5220\u9664'), (b'deleted', '\u5220\u9664\u5b8c\u6bd5'), (b'finished', '\u5168\u90e8\u7ed3\u675f')], default='-1', max_length=20, verbose_name='\u72b6\u6001')),
                ('desc_msg', models.TextField(blank=True, null=True, verbose_name='\u72b6\u6001\u63cf\u8ff0')),
                ('last_update', models.DateTimeField(verbose_name='\u72b6\u6001\u66f4\u65b0\u65f6\u95f4')),
                ('disabled', models.CharField(choices=[(b'1', '\u505c\u6b62'), (b'-1', '\u5f00\u59cb')], default='-1', max_length=2, verbose_name='\u5f00\u59cb\u8fc1\u79fb')),
            ],
            options={
                'db_table': 'ext_account_transfer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtCfilterNewAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField(db_index=True, default=0, help_text='\u6240\u5c5e\u8282\u70b9\uff0cext_cfilter_rule_new\u7684\u4e3b\u952e', verbose_name='\u6240\u5c5e\u89c4\u5219')),
                ('action', models.CharField(choices=[(b'break', '\u4e2d\u65ad\u6267\u884c\u89c4\u5219'), (b'jump_to', '\u8df3\u8fc7\u540e\u9762N\u4e2a\u89c4\u5219'), (b'flag', '\u8bbe\u7f6e\u65d7\u5e1c'), (b'delete', '\u5220\u9664\u90ae\u4ef6'), (b'sequester', '\u9694\u79bb\u90ae\u4ef6'), (b'move_to', '\u79fb\u52a8\u90ae\u4ef6\u81f3\u6587\u4ef6\u5939'), (b'copy_to', '\u590d\u5236\u90ae\u4ef6\u81f3\u6587\u4ef6\u5939'), (b'forward', '\u8f6c\u53d1'), (b'delete_header', '\u5220\u9664\u90ae\u4ef6\u5934'), (b'append_header', '\u8ffd\u52a0\u5934\u90e8'), (b'append_body', '\u8ffd\u52a0\u90ae\u4ef6\u5185\u5bb9'), (b'mail', '\u53d1\u9001\u90ae\u4ef6'), (b'smtptransfer', 'SMTP\u8f6c\u53d1'), (b'replace_subject', '\u90ae\u4ef6\u4e3b\u9898\u66ff\u6362'), (b'replace_body', '\u90ae\u4ef6\u6b63\u6587\u66ff\u6362')], max_length=50, verbose_name='\u52a8\u4f5c')),
                ('value', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u503c')),
                ('sequence', models.IntegerField(default=999, verbose_name='\u52a8\u4f5c\u4f18\u5148\u7ea7')),
            ],
            options={
                'db_table': 'ext_cfilter_new_action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtCfilterNewCond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField(db_index=True, default=0, help_text='\u6240\u5c5e\u8282\u70b9\uff0cext_cfilter_rule_new\u7684\u4e3b\u952e', verbose_name='\u6240\u5c5e\u89c4\u5219')),
                ('parent_id', models.IntegerField(db_index=True, default=0, help_text='\u8fd9\u4e2a\u6761\u4ef6\u7684\u7236\u4eb2ID\uff0c\u903b\u8f91\u5173\u7cfb\u7531parent_id\u6307\u5411\u7684\u90a3\u4e00\u884c\u51b3\u5b9a', verbose_name='\u7236ID')),
                ('logic', models.CharField(choices=[(b'all', '\u6ee1\u8db3\u6240\u6709'), (b'one', '\u6ee1\u8db3\u4efb\u610f')], default='all', help_text='all:\u5e76\u4e14,one\uff1a\u6216', max_length=50, verbose_name='\u903b\u8f91\u8868\u8fbe\u5f0f')),
                ('option', models.CharField(choices=[(b'header', '\u90ae\u4ef6\u5934'), (b'extra', '\u5176\u4ed6')], max_length=50, verbose_name='\u6761\u4ef61')),
                ('suboption', models.CharField(max_length=50, verbose_name='\u6761\u4ef62')),
                ('action', models.CharField(choices=[(b'contains', '\u5305\u542b'), (b'not_contains', '\u4e0d\u5305\u542b'), (b'==', '\u7b49\u4e8e'), (b'>=', '\u5927\u4e8e\u7b49\u4e8e'), (b'<=', '\u5c0f\u4e8e\u7b49\u4e8e'), (b'in', '\u5c5e\u4e8e'), (b'not_in', '\u4e0d\u5c5e\u4e8e')], max_length=50, verbose_name='\u52a8\u4f5c')),
                ('value', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u503c')),
            ],
            options={
                'db_table': 'ext_cfilter_new_cond',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtCfilterRuleNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox_id', models.IntegerField(db_index=True, default=0, help_text='mailbox_id=0\u65f6\u4e3a\u7cfb\u7edf\u8fc7\u6ee4\uff0c\u6709\u503c\u65f6\u4e3a\u7528\u6237\u8fc7\u6ee4', verbose_name='\u90ae\u7bb1ID')),
                ('name', models.CharField(blank=True, help_text='\u7ba1\u7406\u5458\u8f93\u5165\u7684\u89c4\u5219\u5907\u6ce8\uff0c\u53ef\u4e0d\u586b', max_length=150, null=True, verbose_name='\u89c4\u5219\u540d\u79f0')),
                ('type', models.IntegerField(choices=[(-1, '\u53d1\u9001'), (1, '\u63a5\u6536')], default=-1, verbose_name='\u7c7b\u578b')),
                ('logic', models.CharField(choices=[(b'all', '\u6ee1\u8db3\u6240\u6709\u6761\u4ef6'), (b'one', '\u6ee1\u8db3\u4e00\u6761\u5373\u53ef')], default='all', help_text='all\uff1a\u6ee1\u8db3\u6240\u6709\u6761\u4ef6\uff0cone\uff1a\u6ee1\u8db3\u4e00\u6761\u5373\u53ef', max_length=50, verbose_name='\u6761\u4ef6\u5173\u7cfb')),
                ('sequence', models.IntegerField(default=999, verbose_name='\u89c4\u5219\u4f18\u5148\u7ea7')),
                ('disabled', models.IntegerField(choices=[(-1, '\u542f\u7528'), (1, '\u7981\u7528')], default=-1, verbose_name='\u72b6\u6001')),
            ],
            options={
                'db_table': 'ext_cfilter_rule_new',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IMAPMoving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox_id', models.IntegerField(default=0, verbose_name='MailBox')),
                ('mailbox', models.CharField(blank=True, max_length=200, verbose_name='\u672c\u5730\u5e10\u53f7')),
                ('src_mailbox', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8fdc\u7a0b\u5e10\u53f7')),
                ('src_server', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8fdc\u7a0b\u670d\u52a1\u5668')),
                ('ssl', models.CharField(choices=[(b'1', '\u542f\u7528'), (b'-1', '\u4e0d\u542f\u7528')], default='-1', max_length=2, verbose_name='SSL\u8bbf\u95ee')),
                ('src_folder', models.CharField(choices=[(b'all', '\u5168\u90e8'), (b'INBOX', '\u6536\u4ef6\u7bb1')], default='all', max_length=100, verbose_name='\u8fc1\u79fb\u76ee\u5f55')),
                ('src_password', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5bc6\u7801')),
                ('set_from', models.CharField(choices=[(b'file', '\u6587\u4ef6\u5bfc\u5165'), (b'admin', '\u7ba1\u7406\u5458')], default='-1', max_length=20, verbose_name='\u6765\u6e90')),
                ('status', models.CharField(choices=[(b'wait', '\u7b49\u5f85\u5904\u7406'), (b'moving', '\u8fc1\u79fb\u4e2d'), (b'abort', '\u5f02\u5e38\u4e2d\u65ad'), (b'done', '\u8fc1\u79fb\u5b8c\u6bd5')], default='-1', max_length=20, verbose_name='\u72b6\u6001')),
                ('desc_msg', models.TextField(blank=True, null=True, verbose_name='\u72b6\u6001\u63cf\u8ff0')),
                ('last_update', models.DateTimeField(verbose_name='\u72b6\u6001\u66f4\u65b0\u65f6\u95f4')),
                ('disabled', models.CharField(choices=[(b'1', '\u505c\u6b62'), (b'-1', '\u5f00\u59cb')], default='-1', max_length=2, verbose_name='\u6fc0\u6d3b\u72b6\u6001')),
            ],
            options={
                'db_table': 'ext_imapmail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='POP3Moving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.IntegerField(db_index=True, default=0, help_text='\u57df\u540dID', verbose_name='\u57df\u540dID')),
                ('mailbox_id', models.IntegerField(default=0, verbose_name='MailBox')),
                ('src_mailbox', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8fdc\u7a0b\u5e10\u53f7')),
                ('src_server', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8fdc\u7a0b\u670d\u52a1\u5668')),
                ('src_password', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5bc6\u7801')),
                ('disabled', models.CharField(choices=[(b'1', '\u505c\u6b62'), (b'-1', '\u5f00\u59cb')], default='-1', max_length=2, verbose_name='\u6fc0\u6d3b\u72b6\u6001')),
            ],
            options={
                'db_table': 'ext_popmail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox_id', models.IntegerField(default=0, verbose_name='MailBox')),
                ('mailbox', models.CharField(blank=True, max_length=200, verbose_name='\u672c\u5730\u5e10\u53f7')),
                ('server', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8fdc\u7a0b\u670d\u52a1\u5668')),
                ('account', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8fdc\u7a0b\u5e10\u53f7')),
                ('recipient', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6536\u4ef6\u5e10\u53f7')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5bc6\u7801')),
                ('ssl', models.IntegerField(choices=[(b'1', '\u542f\u7528'), (b'-1', '\u4e0d\u542f\u7528')], default='-1', verbose_name='ssl\u767b\u5f55')),
                ('auth', models.IntegerField(choices=[(b'1', '\u662f'), (b'-1', '\u5426')], default='-1', verbose_name='\u9700\u8981\u9a8c\u8bc1')),
                ('fail_report', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8b66\u544a\u90ae\u4ef6\u5730\u5740')),
                ('disabled', models.CharField(choices=[(b'1', '\u7981\u7528'), (b'-1', '\u6fc0\u6d3b')], default='-1', max_length=2, verbose_name='\u6fc0\u6d3b\u72b6\u6001')),
            ],
            options={
                'db_table': 'ext_post_transfer',
                'managed': False,
            },
        ),
    ]
